export const INSURERS = [
  "Intact Financial / Intact Insurance",
  "Aviva Canada",
  "Desjardins Assurances",
  "Wawanesa Mutual Insurance",
  "Co-operators General Insurance",
  "TD Insurance",
  "AIG Canada",
  "RBC Insurance",
  "Sonnet Insurance",
  "Promutuel Assurance",
  "SSQ Assurance",
  "Belairdirect / Belair Insurance",
  "Industrielle Alliance (iA Groupe financier)",
  "Optimum Insurance",
  "The Personal Insurance Company",
  "Chubb Insurance Company of Canada",
  "Peace Hills General Insurance Company",
  "Red River Mutual Insurance",
  "Sandbox Mutual Insurance (formerly SMI)",
  "Pafco Insurance",
  "CAA-Québec Assurance",
  "Economical Insurance",
] as const;

export type Insurer = (typeof INSURERS)[number];

export const INSURER_EMAILS: Record<string, string | null> = {
  "Intact Financial / Intact Insurance": "customer.experience@intact.net",
  "Aviva Canada": "info@avivacanada.com",
  "Desjardins Assurances": null,
  "Wawanesa Mutual Insurance": "TalkToUs@wawanesa.com",
  "Co-operators General Insurance": null,
  "TD Insurance": "tdinscc@TD.com",
  "AIG Canada": null,
  "RBC Insurance": "feedback@rbcinsurance.com",
  "Sonnet Insurance": "help@sonnet.ca",
  "Promutuel Assurance": null,
  "SSQ Assurance": "info@ssq.ca",
  "Belairdirect / Belair Insurance": "customer.experience@belairdirect.com",
  "Industrielle Alliance (iA Groupe financier)": null,
  "Optimum Insurance": null,
  "The Personal Insurance Company": null,
  "Chubb Insurance Company of Canada": "CustomerCare.Canada@chubb.com",
  "Peace Hills General Insurance Company": "phi@phgic.com",
  "Red River Mutual Insurance": "info@redrivermutual.com",
  "Sandbox Mutual Insurance (formerly SMI)": "hello@sandbox.ca",
  "Pafco Insurance": "contactus@pafco.ca",
  "CAA-Québec Assurance": "info@caaquebec.com",
  "Economical Insurance": null,
};
