export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  registerItem: "/register-item",
  lookup: "/lookup",
  lookupPhoto: "/lookup/photo",
  registry: "/registry",
  about: "/about",
  settings: "/settings",
  privacy: "/privacy",
  terms: "/terms",
  faq: "/faq",
  contact: "/contact",
  shop: "/shop",
  shopSuccess: "/shop/success",
  verifyEmail: "/verify-email",
  emailPending: "/email-pending",
  dashboard: "/dashboard",
  edit: (id: string) => `/edit/${id}`,
  reportTheft: "/report-theft",
  adminOrders: "/admin/orders",
  adminOrderDetail: (id: string) => `/admin/orders/${id}`,
  googleCallback: "/auth/google/callback",
  microsoftCallback: "/auth/microsoft/callback",
} as const;
