export const ROUTES = {
  home: "/",
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  register: "/register",
  registerItem: "/register-item",
  lookup: "/lookup",
  lookupPhoto: "/lookup/photo",
  codeScan: (code: string) => `/c/${code}`,
  registry: "/registry",
  about: "/about",
  settings: "/settings",
  profile: "/profile",
  privacy: "/privacy",
  terms: "/terms",
  dataDeletion: "/data-deletion",
  faq: "/faq",
  contact: "/contact",
  shop: "/shop",
  shopSuccess: "/shop/success",
  verifyEmail: "/verify-email",
  emailPending: "/email-pending",
  dashboard: "/dashboard",
  itemDetail: (id: string) => `/items/${id}`,
  edit: (id: string) => `/edit/${id}`,
  reportTheft: "/report-theft",
  admin: "/admin",
  adminItems: "/admin/items",
  adminClients: "/admin/clients",
  adminOrders: "/admin/orders",
  adminOrderDetail: (id: string) => `/admin/orders/${id}`,
  adminProducts: "/admin/products",
  adminProductEdit: (id: string) => `/admin/products/${id}`,
  googleCallback: "/auth/google/callback",
  facebookCallback: "/auth/facebook/callback",
  microsoftCallback: "/auth/microsoft/callback",
} as const;
