export type NavItem = {
  label: string;
  href: string;
  withChevron?: boolean;
};

export type CyclePoint = {
  number: string;
  title: string;
  description: string;
};

export type StepCard = {
  step: string;
  title: string;
  description: string;
  image: string;
};

export type FaqAnswer = string | {
  intro: string;
  bullets: { label: string; text: string }[];
};

export type FaqItem = {
  question: string;
  answer: FaqAnswer;
};

export type TrustBadge = {
  label: string;
};

export type PageSeo = {
  title: string;
  description: string;
};

export type SiteContent = {
  meta: {
    title: string;
    description: string;
  };
  pages: Record<string, PageSeo>;
  nav: {
    items: NavItem[];
    partners: string;
    login: string;
    logout: string;
    myAccount: string;
    myProfile: string;
  };
  hero: {
    subtitleLine1: string;
    titleLine1: string;
    description: string;
    freeLabel: string;
    imageAlt: string;
    trustBadges: TrustBadge[];
  };
  cycle: {
    heading: string;
    imageAlt: string;
    actions: CyclePoint[];
  };
  rollingRegistry: {
    headingLine1: string;
    headingLine2: string;
    description: string;
    tagline: string;
    imageAlt: string;
    viewCategoriesLink: string;
  };
  allCategories: {
    heading: string;
    description: string;
    toggleButton: string;
    items: string[];
  };
  protectionCta: {
    headingLine1: string;
    headingLine2: string;
    description: string;
    imageAlt: string;
  };
  threeSteps: {
    heading: string;
    subtitle: string;
    learnMoreLink: string;
    steps: StepCard[];
  };
  faq: {
    heading: string;
    description: string;
    buttonText: string;
    items: FaqItem[];
  };
  footer: {
    subscribeHeading: string;
    emailPlaceholder: string;
    sendButton: string;
    disclaimer: string;
    privacyPolicy: string;
    termsOfUse: string;
    dataDeletion: string;
    cookieSettings: string;
    copyright: string;
    promoLine?: string;
  };
  buttons: {
    registerItem: string;
    declareStolen: string;
    signUp: string;
    verifyItem: string;
  };
  a11y: {
    skipToContent: string;
    mainNav: string;
    mobileNav: string;
    logoAlt: string;
  };
  auth?: {
    loginHeading: string;
    loginDescription: string;
    registerHeading: string;
    registerDescription: string;
    emailLabel: string;
    passwordLabel: string;
    passwordHint: string;
    firstNameLabel: string;
    lastNameLabel: string;
    phoneLabel: string;
    optional: string;
    loginButton: string;
    loggingIn: string;
    registerButton: string;
    registering: string;
    noAccount: string;
    registerLink: string;
    hasAccount: string;
    loginLink: string;
    orSeparator: string;
    googleButton: string;
    facebookButton: string;
    microsoftButton: string;
    oauthLoading: string;
    oauthError: string;
    oauthNoEmail: string;
    oauthEmailPrompt: string;
    socialAccountError: string;
    termsLabel: string;
    termsLink: string;
    termsAnd: string;
    privacyLink: string;
  };
  dashboard?: {
    heading: string;
    welcome: string;
    noItems: string;
    addItem: string;
    reportTheft: string;
    statuses: Record<string, string>;
    alreadyInCartTitle: string;
    alreadyInCartDescription: string;
    alreadyInCartConfirm: string;
    alreadyInCartCancel: string;
    alreadyInCartViewCart: string;
    awaitingNumber: string;
    noNumberHint: string;
    clientNumber: string;
    editItem: string;
  };
  editItem?: {
    heading: string;
    saveButton: string;
    saving: string;
    success: string;
    error: string;
    notFound: string;
    backToDashboard: string;
    recoverButton: string;
    recoverConfirm: string;
    recoverConfirmButton: string;
    recoverCancel: string;
    recovering: string;
  };
  settings?: {
    heading: string;
    communicationHeading: string;
    communicationDescription: string;
    languageLabel: string;
    saveButton: string;
    saving: string;
    successMessage: string;
  };
  profile?: {
    heading: string;
    description: string;
    personalInfoHeading: string;
    addressHeading: string;
    addressDescription: string;
    address1Label: string;
    address2Label: string;
    cityLabel: string;
    provinceLabel: string;
    postalCodeLabel: string;
    saveButton: string;
    saving: string;
    successMessage: string;
    backToDashboard: string;
  };
  archive?: {
    button: string;
    modalTitle: string;
    modalDescription: string;
    reasons: Record<string, string>;
    customReasonPlaceholder: string;
    confirmButton: string;
    archiving: string;
    cancelButton: string;
    stolenWarning: string;
    archivedItems: string;
    archivedOn: string;
    reason: string;
    noArchivedItems: string;
  };
  transfer?: {
    button: string;
    comingSoon: string;
  };
  registration?: {
    heading: string;
    description: string;
    step1Title: string;
    step2Title: string;
    step3Title: string;
    step4Title: string;
    categoryLabel: string;
    categoryPlaceholder: string;
    nameLabel: string;
    brandLabel: string;
    modelLabel: string;
    yearLabel: string;
    serialLabel: string;
    serialExplanation: string;
    valueLabel: string;
    yearInvalidError: string;
    valueIntegerError: string;
    valueMinError: string;
    descriptionLabel: string;
    descriptionHelper: string;
    termsCheckbox: string;
    continueButton: string;
    backButton: string;
    photosHeading: string;
    photosDescription: string;
    dropzoneText: string;
    documentsHeading: string;
    documentsDescription: string;
    addDocumentButton: string;
    confirmButton: string;
    submitting: string;
    successHeading: string;
    successDescription: string;
    successNoNumber: string;
    rnbpNumberLabel: string;
    goToDashboard: string;
    stickerHeading: string;
    stickerPitch: string;
    stickerCta: string;
    addToCart: string;
    addedToCart: string;
    viewShop: string;
  };
  shop?: {
    heading: string;
    productName: string;
    productDescription: string;
    productFeatures: string[];
    productImageAlt: string;
    priceLabel: string;
    quantityLabel: string;
    buyButton: string;
    cartTitle: string;
    cartEmpty: string;
    cartEmptyAction: string;
    checkout: string;
    checkingOut: string;
    removeItem: string;
    subtotal: string;
    perSheet: string;
    successHeading: string;
    successDescription: string;
    backToShop: string;
    backToHome: string;
    orderStickers: string;
    selectItemLabel: string;
    noItemsMessage: string;
    noItemsLink: string;
    loginRequired: string;
    loginLink: string;
    addButton: string;
    comingSoonBanner: string;
    comingSoonCheckout: string;
    loadingProducts: string;
    loadError: string;
    freePrice: string;
    forWhichItem: string;
    confirmAdd: string;
  };
  report?: {
    heading: string;
    description: string;
    successHeading: string;
    successDescription: string;
    noActiveItems: string;
    itemLabel: string;
    itemPlaceholder: string;
    policeReportLabel: string;
    theftDateLabel: string;
    theftLocationLabel: string;
    descriptionLabel: string;
    submitting: string;
    submitButton: string;
  };
  lookup?: {
    heading: string;
    description: string;
    inputLabel: string;
    inputPlaceholder: string;
    inputHint?: string;
    searchButton: string;
    searching: string;
    foundMessage: string;
    stolenMessage: string;
    notFoundMessage: string;
    photoSearchLink?: string;
  };
  partners?: {
    heading: string;
    description: string;
    tabs: { citizen: string; police: string; insurer: string };
    consultButton: string;
    citizenDescription: string;
    citizenWhyTitle: string;
    citizenAdvantages: { title: string; text: string }[];
    policeWhyTitle: string;
    insurerWhyTitle: string;
    contactButton: string;
    policeAccordion: {
      title: string;
      intro: string;
      subheading: string;
      advantages: { title: string; text: string }[];
    };
    insurerAccordion: {
      title: string;
      intro: string;
      subheading: string;
      advantages: { title: string; text: string }[];
      quote: string;
    };
    ctaDescription: string;
    formHeading: string;
    nameLabel: string;
    emailLabel: string;
    companyLabel: string;
    typeLabel: string;
    messageLabel: string;
    typePlaceholder: string;
    typeOptions: { insurer: string; retailer: string; security: string; other: string };
    submitButton: string;
    submitting: string;
    successMessage: string;
    errorMessage: string;
  };
  contact?: {
    heading: string;
    description: string;
    nameLabel: string;
    emailLabel: string;
    phoneLabel: string;
    phonePlaceholder: string;
    messageLabel: string;
    submitButton: string;
    submitting: string;
    successMessage: string;
    emailError: string;
    errorMessage: string;
  };
  about?: {
    heading: string;
    paragraphs: string[];
  };
  promo?: {
    badge: string;
    text: string;
    cta: string;
    dismiss: string;
    dontShowAgain?: string;
    calloutDashboard?: string;
    calloutItem?: string;
    calloutRegistration?: string;
  };
  legal?: {
    privacyHeading: string;
    privacyContent: { title: string; body: string }[];
    termsHeading: string;
    termsContent: { title: string; body: string }[];
    dataDeletion: {
      heading: string;
      intro: string;
      stepsHeading: string;
      steps: string[];
      timelineHeading: string;
      timeline: string;
      contactHeading: string;
      contactBody: string;
    };
  };
  insurance?: {
    heading: string;
    promo: string;
    description: string;
    featuredHeading: string;
    featuredHint: string;
    moreButton: string;
    moreDescription: string;
    composerHeading: string;
    composerDescription: string;
    selectedSummary: string;
    selectLabel: string;
    selectPlaceholder: string;
    messageLabel: string;
    messageTemplate: string;
    sendButton: string;
    copiedToast: string;
    emailSubject: string;
    emailButton: string;
  };
  verifyBeforeBuy?: {
    headingAccent: string;
    heading: string;
    description: string;
    buttonText: string;
    imageAlt: string;
  };
  emailPending?: {
    heading: string;
    description: string;
    resendButton: string;
    resendSuccess: string;
    logoutButton: string;
    checkAgain: string;
    notVerifiedYet: string;
  };
  errors?: {
    serviceUnavailable: string;
    serviceUnavailableDescription: string;
    notFound: string;
    notFoundDescription: string;
    backHome: string;
    generic: string;
    loadError: string;
    loginError: string;
    registerError: string;
    verificationError: string;
    invalidVerificationLink: string;
    tryAgain: string;
    newsletterThanks: string;
    newsletterError: string;
    newsletterUnavailable: string;
  };
  admin?: {
    nav: {
      dashboard: string;
      items: string;
      orders: string;
      products: string;
    };
    dashboard: {
      title: string;
      totalUsers: string;
      totalItems: string;
      ordersCompleted: string;
      revenue: string;
      chartsTitle: string;
      registrations: string;
      itemsRegistered: string;
      revenueOverTime: string;
      itemsByCategory: string;
      periodPreview?: string;
      periodDay: string;
      periodWeek: string;
      periodMonth: string;
      axisCount?: string;
      axisRevenue?: string;
      axisDayOfMonth?: string;
      axisWeekNumber?: string;
      axisMonth?: string;
      axisItemCount?: string;
      serverMetrics: string;
      live: string;
      cpu: string;
      ram: string;
      nodeHeap: string;
      dbSize: string;
      connections: string;
      reqPerMin: string;
      uptime: string;
      activityFeed: string;
      noActivity: string;
    };
    products: {
      title: string;
      addProduct: string;
      noProducts: string;
      slug: string;
      price: string;
      active: string;
      inactive: string;
      sortOrder: string;
      customMechanic: string;
      editTitle: string;
      createTitle: string;
      nameFr: string;
      nameEn: string;
      descriptionFr: string;
      descriptionEn: string;
      featuresFr: string;
      featuresEn: string;
      featuresHint: string;
      priceCents: string;
      priceDollars: string;
      stripePriceId: string;
      imageUrl: string;
      isActive: string;
      save: string;
      saving: string;
      create: string;
      creating: string;
      back: string;
      success: string;
      created: string;
      error: string;
      notFound: string;
      customMechanicBadge: string;
    };
  };
  apiErrors?: Record<string, string>;
};
